services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - vw_redis:/data

  qdrant:
    image: qdrant/qdrant:v1.9.3
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - vw_qdrant:/qdrant/storage

volumes:
  vw_redis:
  vw_qdrant:
